# Generated by Django 4.0.4 on 2022-05-06 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('phone', models.PositiveBigIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
