# Generated by Django 4.0.4 on 2022-05-07 13:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_dealer_play_player_dealer'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('Day', 'Day'), ('Night', 'Night')], max_length=5)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.dealer')),
                ('plays', models.ManyToManyField(related_name='Plays', to='web.play')),
            ],
        ),
    ]
