# Generated by Django 4.0.4 on 2022-05-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_list_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='phone',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
