# Generated by Django 4.0.4 on 2022-05-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_player_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='collectPick3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='pick3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='rewardPick3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
