# Generated by Django 4.0.4 on 2022-05-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_list_collectpick3_list_pick3_list_rewardpick3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='collectPick3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='list',
            name='rewardPick3',
            field=models.IntegerField(default=0),
        ),
    ]
