# Generated by Django 4.0.4 on 2022-05-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_list_collectpick3_alter_list_rewardpick3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='collectPick3',
            new_name='collectPick3Bola',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='rewardPick3',
            new_name='collectPick3Box',
        ),
        migrations.AddField(
            model_name='list',
            name='collectPick3Strike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='list',
            name='collectPick3Total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='list',
            name='rewardPick3Bola',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='list',
            name='rewardPick3Box',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='list',
            name='rewardPick3Strike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='list',
            name='rewardPick3Total',
            field=models.IntegerField(default=0),
        ),
    ]
