# Generated by Django 4.0.4 on 2022-05-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_rename_collectpick3_list_collectpick3bola_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='pick3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='play',
            name='rewardPick3Bola',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='play',
            name='rewardPick3Box',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='play',
            name='rewardPick3Strike',
            field=models.IntegerField(default=0),
        ),
    ]
