# Generated by Django 4.0.4 on 2022-05-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_play_pick3_play_rewardpick3bola_play_rewardpick3box_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
